### ISSUE TITLE
fs-xattr fails to install with node v12 (osx)

### ISSUE THREAD

**Issue by dlhsiao** [LinusU/fs-xattr#27]
Node's LTS must of updated a couple of days ago to v12.0.0, and suddenly fs-xattr errored out when trying to install. I've re-installed Node v10 for now, but I thought you should know.

>\> fs-xattr@0.1.17 install /Users/travis/build/dlhsiao/code.pyret.org/node_modules/fs-xattr
\> node-gyp rebuild
  CXX(target) Release/obj.target/xattr/src/async.o
../src/async.cc:35:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(1, argv);
              ^
../../nan/nan.h:1673:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:103:40: note: expanded from macro 'NAN_DEPRECATED'
\# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/async.cc:52:46: error: no matching member function for call to 'ToObject'
    v8::Local<v8::Object> bufferObj = value->ToObject();
                                      ~~~~~~~^~~~~~~~
/Users/travis/.node-gyp/12.0.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/travis/.node-gyp/12.0.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
../src/async.cc:129:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(2, argv);
              ^
../../nan/nan.h:1673:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:103:40: note: expanded from macro 'NAN_DEPRECATED'
\# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/async.cc:186:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(2, argv);
              ^
../../nan/nan.h:1673:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:103:40: note: expanded from macro 'NAN_DEPRECATED'
\# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
3 warnings and 1 error generated.
make: *** [Release/obj.target/xattr/src/async.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/travis/.nvm/versions/node/v12.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/Users/travis/.nvm/versions/node/v12.0.0/bin/node" "/Users/travis/.nvm/versions/node/v12.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/travis/build/dlhsiao/code.pyret.org/node_modules/fs-xattr
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by jclark-dot-org** [comment]
Seeing the same with 0.1.17 and 0.2.1

**Comment by donburks** [comment]
Yeah, having the same issue, and it's getting in the way of a lot of other installs.

**Comment by LinusU** [comment]
Sorry for the delay in this, I'll try to get to it tonight ☺️

**Comment by LinusU** [comment]
@dlhsiao, @jclark-dot-org, @donburks could you help me try out #29 which should fix this?

```sh
npm install LinusU/fs-xattr#node-12
```

**Comment by donburks** [comment]
Worked for me.

**Comment by LinusU** [comment]
Thanks! Merging 🚀

**Comment by LinusU** [comment]
Released as 0.3.0 🚢

**Comment by cjsauer** [comment]
This is still broken for me, with the following compilation error:

```
../src/async.cc:52:46: error: no matching member function for call to 'ToObject'
    v8::Local<v8::Object> bufferObj = value->ToObject();
```

**Comment by donburks** [comment]
I'm back, now I'm having the same issue with:

```
../src/async.cc:52:46: error: no matching member function for call to 'ToObject'
    v8::Local<v8::Object> bufferObj = value->ToObject();
```

Being my output.

**Comment by at-cuongtran** [comment]
I got the same issue as @donburks. I tried to downgrade node to 10 but it doesn't solve it.

**Comment by felipepanegalli** [comment]
If continue the problem, make a downgrade for node 11 or 10. npm i -g node@11 or 10.
This solution works for me.

**Comment by LinusU** [comment]
@cjsauer @donburks are you sure that you are using the 0.3.0 version? Both of your errors references `async.cc`, but this file doesn't exist any longer in the 0.3.0 version 🤔

**Comment by shikhars371** [comment]
not working on node 12 on OSX , but runs on 11
